### ISSUE TITLE
USB Flags bad quotation marks under windows

### ISSUE THREAD

**Issue by Louis2016** [jantje/arduino-eclipse-plugin#305]
Hi,
- Windows 7 32 bits

When trying to compile with a board that defines USB_MANUFACTURER and USB_PRODUCT (atmega32u4 boards), the following compilation error occurs:

avr-g++: '-DUSB_MANUFACTURER=Unknown': No such file or directory
avr-g++: '-DUSB_PRODUCT=SparkFun Fio v3': No such file or directory
make: *** [Test.cpp.o] Error 1

The environment variable ${A.BUILD.USB_FLAGS} is defined as:

-DUSB_VID=${A.BUILD.VID} -DUSB_PID=${A.BUILD.PID} '-DUSB_MANUFACTURER=${A.BUILD.USB_MANUFACTURER}' '-DUSB_PRODUCT=${A.BUILD.USB_PRODUCT}'

${A.BUILD.USB_FLAGS} should be defined as:

-DUSB_VID=${A.BUILD.VID} -DUSB_PID=${A.BUILD.PID} -DUSB_MANUFACTURER="""${A.BUILD.USB_MANUFACTURER}""" -DUSB_PRODUCT="""${A.BUILD.USB_PRODUCT}"""

When A.BUILD.USB_MANUFACTURER="Something here"
and A.BUILD.USB_PRODUCT="Something here"

Note on Eclipse Arduino "versions":
- it works with 2.3
- with nightly builds, A.BUILD.USB_FLAGS value is restored when compiling (by whom, from where and why?)

Proposed fix tested and it works under Windows,
Regards

Edit: more portable

${A.BUILD.USB_FLAGS} should be defined as:

-DUSB_VID=${A.BUILD.VID} -DUSB_PID=${A.BUILD.PID} -DUSB_MANUFACTURER=${A.BUILD.USB_MANUFACTURER} -DUSB_PRODUCT=${A.BUILD.USB_PRODUCT}

With A.BUILD.USB_MANUFACTURER="\"Something here"\"
and A.BUILD.USB_PRODUCT="\"Something here"\"

**Comment by jantje** [comment]
this is a duplicate of #263
